# TCL File Generated by Component Editor 13.0sp1
# Wed Mar 14 19:34:08 GMT 2018
# DO NOT MODIFY


# 
# ah_instr "ah_instr" v1.0
#  2018.03.14.19:34:07
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ah_instr
# 
set_module_property DESCRIPTION ""
set_module_property NAME ah_instr
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ah_instr
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ah_custom_instruction
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ah_custom_instruction.v VERILOG PATH ip/ah_custom_instruction.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter M_ADDR_WIDTH INTEGER 26 ""
set_parameter_property M_ADDR_WIDTH DEFAULT_VALUE 26
set_parameter_property M_ADDR_WIDTH DISPLAY_NAME M_ADDR_WIDTH
set_parameter_property M_ADDR_WIDTH TYPE INTEGER
set_parameter_property M_ADDR_WIDTH ENABLED false
set_parameter_property M_ADDR_WIDTH UNITS None
set_parameter_property M_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property M_ADDR_WIDTH DESCRIPTION ""
set_parameter_property M_ADDR_WIDTH HDL_PARAMETER true
add_parameter M_DATA_WIDTH INTEGER 32 ""
set_parameter_property M_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property M_DATA_WIDTH DISPLAY_NAME M_DATA_WIDTH
set_parameter_property M_DATA_WIDTH TYPE INTEGER
set_parameter_property M_DATA_WIDTH ENABLED false
set_parameter_property M_DATA_WIDTH UNITS None
set_parameter_property M_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property M_DATA_WIDTH DESCRIPTION ""
set_parameter_property M_DATA_WIDTH HDL_PARAMETER true
add_parameter BYTEENABLEWIDTH INTEGER 4 ""
set_parameter_property BYTEENABLEWIDTH DEFAULT_VALUE 4
set_parameter_property BYTEENABLEWIDTH DISPLAY_NAME BYTEENABLEWIDTH
set_parameter_property BYTEENABLEWIDTH TYPE INTEGER
set_parameter_property BYTEENABLEWIDTH ENABLED false
set_parameter_property BYTEENABLEWIDTH UNITS None
set_parameter_property BYTEENABLEWIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BYTEENABLEWIDTH DESCRIPTION ""
set_parameter_property BYTEENABLEWIDTH HDL_PARAMETER true
add_parameter control_go_idle STD_LOGIC_VECTOR 1
set_parameter_property control_go_idle DEFAULT_VALUE 1
set_parameter_property control_go_idle DISPLAY_NAME control_go_idle
set_parameter_property control_go_idle WIDTH 2
set_parameter_property control_go_idle TYPE STD_LOGIC_VECTOR
set_parameter_property control_go_idle ENABLED false
set_parameter_property control_go_idle UNITS None
set_parameter_property control_go_idle ALLOWED_RANGES 0:2
set_parameter_property control_go_idle HDL_PARAMETER true
add_parameter control_go_en STD_LOGIC_VECTOR 2 ""
set_parameter_property control_go_en DEFAULT_VALUE 2
set_parameter_property control_go_en DISPLAY_NAME control_go_en
set_parameter_property control_go_en WIDTH 2
set_parameter_property control_go_en TYPE STD_LOGIC_VECTOR
set_parameter_property control_go_en ENABLED false
set_parameter_property control_go_en UNITS None
set_parameter_property control_go_en ALLOWED_RANGES 0:2
set_parameter_property control_go_en DESCRIPTION ""
set_parameter_property control_go_en HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave result result Output 32
add_interface_port nios_custom_instruction_slave clk_instr clk Input 1
add_interface_port nios_custom_instruction_slave reset_instr reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 10
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output M_ADDR_WIDTH
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_byteenable byteenable Output BYTEENABLEWIDTH
add_interface_port avalon_master master_readdata readdata Input M_DATA_WIDTH
add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_burstcount burstcount Output 1
add_interface_port avalon_master master_waitrequest waitrequest Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock ""
set_interface_property reset_sink synchronousEdges NONE
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_master reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 50000000
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_master clk Input 1

