# TCL File Generated by Component Editor 13.0sp1
# Mon Mar 12 17:28:31 GMT 2018
# DO NOT MODIFY


# 
# ahfp_mult "ahfp_mult" v1.0
#  2018.03.12.17:28:31
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ahfp_mult
# 
set_module_property DESCRIPTION ""
set_module_property NAME ahfp_mult
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ahfp_mult
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

