# TCL File Generated by Component Editor 13.0sp1
# Tue Feb 20 19:07:48 GMT 2018
# DO NOT MODIFY


# 
# ahfp_mult "ahfp_mult" v1.0
#  2018.02.20.19:07:48
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ahfp_mult
# 
set_module_property DESCRIPTION ""
set_module_property NAME ahfp_mult
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ahfp_mult
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ahfp_mult
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ahfp_mult.v VERILOG PATH design_files/ahfp_mult.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL ahfp_mult
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ahfp_mult.v VERILOG PATH design_files/ahfp_mult.v


# 
# parameters
# 
add_parameter bias STD_LOGIC_VECTOR 127
set_parameter_property bias DEFAULT_VALUE 127
set_parameter_property bias DISPLAY_NAME bias
set_parameter_property bias TYPE STD_LOGIC_VECTOR
set_parameter_property bias UNITS None
set_parameter_property bias ALLOWED_RANGES 0:255
set_parameter_property bias HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave datab datab Input 32
add_interface_port nios_custom_instruction_slave result result Output 32

